services:
  #Nginx Service
   webserver:
     image: nginx:alpine
     container_name: webserver
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
   dbserver:
     image: postgres:alpine
     container_name: psqldb
     restart: unless-stopped
     ports:
       - "5432:5432"