version: "3.9"
services:
    webserver:
        build: 
            context: .
            dockerfile: Dockerfile_nginx
        image: jppadilla/mynginx:1.0
    customhttpd:
        build: 
            context: .
            dockerfile: Dockerfile_httpd
        image: jppadilla/myhttpd:1.0
        
